permalink: pretty
theme: minima
url: "https://jonaslalin.com"

defaults:
  - scope:
      path: ""
      types: posts
    values:
      layout: post

exclude:
  - README.md

title: I, Deep Learning
description: Yet another blog about deep learning.
author: Jonas Lalin
github_username: jonaslalin
google_analytics: G-XY9F18W0CY
